development:
  adapter: mysql2
  encoding: utf8
  database: dunson_brewing_development
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: dunson_brewing_test
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
